### ISSUE TITLE
CommandLine Repository Permission Denied

### ISSUE THREAD

**Issue by Cam1337** [beltex/dshb#24]
cam$ git clone --recursive https://github.com/beltex/dshb

Cloning into 'dshb'...
remote: Counting objects: 810, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 810 (delta 106), reused 82 (delta 82), pack-reused 679
Receiving objects: 100% (810/810), 259.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (545/545), done.
Checking connectivity... done.
Submodule 'libs/CommandLine' (git@github.com:jatoben/CommandLine.git) registered for path 'libs/CommandLine'
Submodule 'libs/SMCKit' (git@github.com:beltex/SMCKit.git) registered for path 'libs/SMCKit'
Submodule 'libs/SystemKit' (git@github.com:beltex/SystemKit.git) registered for path 'libs/SystemKit'
Cloning into 'libs/CommandLine'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:jatoben/CommandLine.git' into submodule path 'libs/CommandLine' failed

**Comment by beltex** [comment]
Hi @Cam1337!

This [GitHub help page](https://help.github.com/articles/error-permission-denied-publickey/) should cover the error. It’s an issue with your SSH key setup.

However, you bring to the fore a good point! That is, the Git submodules for the project are using SSH URLs instead of HTTPS, which makes things less accessible, since SSH keys must be generated and synced with a GitHub account, just to clone the repository. I should have realized this earlier, my mistake! I’ve thus updated the submodule URLs.

Give it a shot now and let me know if it works for you!

**Comment by Cam1337** [comment]
Hi @beltex, 

I managed to download all of the files. Now the problem occurs with the build. I have pasted the log here: https://gist.github.com/Cam1337/252994576d1a18dee29e

Please let me know if you have any suggestions.

Best,
  Cameron

**Comment by beltex** [comment]
Awesome!

Looking at the logs, seems to be due to the Xcode version. **Xcode 6.3 beta 3** is required, which includes the Swift 1.2 compiler, available [here](https://developer.apple.com/xcode/downloads/). You can check the Swift compiler version you have like so

```bash
$ xcrun swiftc -v
Apple Swift version 1.2 (swiftlang-602.0.44.6 clang-602.0.45)
Target: x86_64-apple-darwin14.1.0
```

Once you've downloaded it and put it in place, make sure to run the following to set it as the active Xcode

```bash
$ sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/
```

**Comment by Cam1337** [comment]
It works! Thank you very much for your timely responses. 

Regards,
Cameron

**Comment by beltex** [comment]
Great! np! :)
